
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.credibil-core]
audit-as-crates-io = true

[[exemptions.cc]]
version = "1.2.45"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.credibil-core]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.icu_collections]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_locale_core]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer_data]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_properties]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_properties_data]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_provider]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.iri-string]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.82"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-http]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-otlp]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-proto]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.14.1"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.14.1"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.42"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.tinystr]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.tonic]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.tonic-prost]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.43"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.35"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.32.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.22"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.55"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.82"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.writeable]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.yoke]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerotrie]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.zerovec]]
version = "0.11.5"
criteria = "safe-to-deploy"
