
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.credibil-core]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.atomic-waker]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.41"
criteria = "safe-to-deploy"

[[exemptions.credibil-core]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.io-uring]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.iri-string]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.30.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-http]]
version = "0.30.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-otlp]]
version = "0.30.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-proto]]
version = "0.30.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.30.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.13.5"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.13.5"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.17"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.6"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.tonic]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.50"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.26"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.26"
criteria = "safe-to-deploy"
