name: Prepare release notes
description: Prepare release notes for the upcoming release

inputs:
  release-version:
    description: The version of the release to archive.
    required: true
  next-version:
    description: The version to use to create release notes.
    required: true

# git reset --hard origin/${{ steps.latest.outputs.branch }}
runs:
  using: composite
  steps:
    - name: Archive previous release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -ex
        version_x=$(echo ${{ inputs.release-version }} | sed 's/.$/x/')
        sed -i "/ARCHIVE_START/a * [$version_x](https://github.com/${{ github.repository }}/blob/release-${{ inputs.release-version }}/RELEASES.md)" RELEASES.md

    - name: Create next release notes
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -ex
        sed -i '0,/---/d' RELEASES.md
        archive=$(cat RELEASES.md)

        cat > RELEASES.md <<EOF
        ## ${{ inputs.next-version }}

        Unreleased

        ### Added

        ### Changed

        ---
        $archive
        EOF

        git commit -am "Update release notes for ${{ inputs.next-version }}"
        git push origin HEAD:ci/next-${{ inputs.next-version }}
