[package]
name = "credibil-api"
edition.workspace = true

[lints]
workspace = true

[dependencies]
bytes = "1.10.1"
http.workspace = true
http-body = "1.0.1"
http-body-util = "0.1"
serde.workspace = true
serde_json.workspace = true
