[package]
name = "credibil-urlencode"
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
percent-encoding = "2.3.1"
serde.workspace = true
serde_json.workspace = true
