name: ci

on:
  push:
    paths:
      - '**/src/**'
      - '**/tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - '**/src/**'
      - '**/tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true
# permissions:
#   contents: read
# env:
#   RUSTFLAGS: -Dwarnings

jobs:
  verify:
    uses: credibil/pipeline/.github/workflows/verify.yaml@main
    # with:
    #   toolchain: stable
    #   target: x86_64-unknown-linux-gnu
    #   features: "full"