name: Create Patch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  skip:
    name: Skipped
    if: ${{ !startsWith(github.ref_name, 'release-') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow only runs on the 'release-*' branches"
      - run: exit 1
          
  # Increment patch version and update RELEASES.md
  # Push back to the release-<version> branch for review and publishing
  patch:
    name: Bump patch version
    if: startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        
      - name: Set git identity
        uses: ./.github/actions/git-identity

      - name: Install cargo-release
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-release

      - name: Bump version
        run: cargo release version patch --execute --no-confirm

      - name: Patch version
        id: patch
        run: |
          set -ex
          version=$(grep '^version =' Cargo.toml | head -n 1 | sed 's/.*"\(.*\)"/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Update release notes
        uses: ./.github/actions/release-notes
        with:
          version: ${{ steps.patch.outputs.version }}
          branch: ${{ github.ref_name }}
