name: Publish Release

on:
  workflow_dispatch:

jobs:
  tag:
    name: Tag release
    if: startsWith(github.ref_name, 'release-')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: |
          echo ${{ github.ref_name }}

      - name: Set git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Get latest release
        id: latest
        uses: ./.github/actions/latest-release
        
      - name: Update release notes
        run: |
          set -ex
          sed -i "s/^Unreleased/Released $(date +'%Y-%m-%d')/" RELEASES.md
          git commit --allow-empty -am "Release ${{ steps.latest.outputs.branch }}"
          # git push origin HEAD:${{ steps.latest.outputs.branch }}
          git push 

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.latest.outputs.version }}

  release:
    name: Create GitHub release
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get release notes
        id: notes
        run: |
          notes="$(cat RELEASES.md)"
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$notes" >> $GITHUB_OUTPUT
          echo "---" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.tag.outputs.tag }}
          name: Release ${{ needs.tag.outputs.tag }}
          body: ${{ steps.notes.outputs.release_notes }}
          generateReleaseNotes: true # add link to full changelog
          
          # bodyFile: https://github.com/${{ github.repository }}/blob/${{ steps.latest.outputs.branch }}/RELEASES.md
