name: Release

on:
  workflow_dispatch:
  # release:
  #   types: [published]
permissions:
  contents: write

jobs:
  version:
    # uses: credibil/pipeline/.github/workflows/release.yaml@main
    # with:
    #   version: 1.1.2
    name: Set version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      # get current version
      - name: Get current version
        id: current
        run: |
          set -ex
          version=$(grep '^version =' Cargo.toml | head -n 1 | sed 's/.*"\(.*\)"/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT

      # # calculate minimum version bump required
      # - uses: taiki-e/install-action@v2
      #   with:
      #     tool: cargo-semver-checks
      # - run: cargo build --manifest-path crates/ci/Cargo.toml
      # - name: Calculate version bump
      #   id: bump
      #   run: |
      #     level=$(./target/debug/calculate-version)
      #     echo "level=$level" >> $GITHUB_OUTPUT

      # set committer's git identity
      - name: Set identity 
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      # bump version
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-release
      - name: Release
        run: cargo release version minor --execute --no-confirm
      
      # check semver against previous release
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          baseline-rev: v${{ steps.current.outputs.version }}
          
      - name: Get release version
        id: release
        run: |
          set -ex
          version=$(grep '^version =' Cargo.toml | head -n 1 | sed 's/.*"\(.*\)"/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create release branch
        run: |
          echo "Release version: ${{ steps.release.outputs.version }}"
          git push origin HEAD:release-${{ steps.release.outputs.version }}
          git checkout -b release-${{ steps.release.outputs.version }}


    # 5. create candidate changelog/release notes
    # 6. create draft PR to main branch
    # 7. on merge, create tag and release