name: Release

on:
  push:
    paths:
      - '**/src/**'
      - '**/tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  version:
    uses: credibil/pipeline/.github/workflows/release.yaml@main
    with:
      version: 1.1.2