name: ci

on:
  push:
    paths:
      - '**/src/**'
      - '**/tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - '**/src/**'
      - '**/tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  verify:
    uses: credibil/pipeline/.github/workflows/verify.yaml@main
    # with:
    #   toolchain: stable
    #   target: x86_64-unknown-linux-gnu
    #   features: "full"