name: Version

on:
  push:
    paths:
      - '**/src/**'
      - '**/tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  version:
    uses: credibil/pipeline/.github/workflows/version.yaml@main
    with:
      version: 1.1.2
    #   toolchain: stable
    #   target: x86_64-unknown-linux-gnu
    #   features: "full"